---
body-required: true

subject:
  - severity: warning
    expression: ^[0-9]+
    name: useless warning for a test

external-tools:
  - severity: error
    name: gofmt
    command:
      - make
      - fmt-run
  - severity: error
    name: unit tests
    command:
      - make
      - test
