project_name: git-commit
builds:
  - binary: git-hook-commit
    main: ./cmd/main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - x86
    ldflags: -s -w -X livingit.de/code/git-commit/cmd/methods.versionNumber={{.Version}} -X livingit.de/code/git-commit/cmd/methods.commit={{.Commit}} -X livingit.de/code/git-commit/cmd/methods.date={{.Date}}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.Commit}}

nfpm:
    vendor: Sascha Andres
    homepage: https://livingit.de
    maintainer: Sascha Andres <sascha.andres@outlook.com>
    description: git commit hook implementation
    license: Apache 2.0
    formats:
      - deb
    dependencies:
      - git
    bindir: /usr/local/bin

release:
  draft: true
  github:
      owner: sascha-andres
      name: git-commit

